service: aws-lambda-ssm-extension
frameworkVersion: '3'

params:
  default:
    ssmParam: /demo/param

provider:
  name: aws
  runtime: nodejs18.x
  logRetentionInDays: 1
  region: us-east-1
  environment:
    SSM_PARAMETER_STORE_TTL: 10
    PARAMETERS_SECRETS_EXTENSION_HTTP_PORT: 2773
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameters
            - kms:Decrypt
          Resource: '*'

functions:
  ssmTest:
    handler: src/index.handler
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
